services:
  db:
    image: "mariadb:11"
    ports:
      - "3390:3306"
    expose:
      - "3390"
    volumes:
      - "./schema:/docker-entrypoint-initdb.d"
    healthcheck:
      test: "healthcheck.sh --su-mysql  --connect --innodb_initialized"
      interval: 2s
      retries: 30
    environment:
      MARIADB_ROOT_PASSWORD: root-pw
      MARIADB_DATABASE: chitchat
      MARIADB_USER: chitchat
      MARIADB_PASSWORD: password
  chitchat:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_HOSTNAME: db
      DB_PORT: 3306
      DB_USERNAME: "chitchat"
      DB_PASSWORD: "password" # wow, so creative

      # Set to anything, but "development" to get app out of dev-mode
      # This disables debug-logging and pretty-printing of logs for now, but will,
      # in time for 2.0, also change behaviour in regard to verification of email.
      MODE: "development"

      # Set to what will be the public URL. May for instance be https://example.com
      # PS: path is not supported. If you need such facilities, please create a PR :)
      PUBLIC_URL: "http://localhost:3333"

      # The port the server will be listening on
      PORT: 3333